<a href="https://colab.research.google.com/github/175329/Mineria-de-datos/blob/main/MineriaDeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de datos

##Primer parcial

###Introducción

####Conceptos

Minería de datos: Es una disciplina que utiliza técnicas de análisis estadístico y aprendizaje automático para extraer información valiosa de grandes conjuntos de datos. Este proceso implica la exploración y análisis de datos para identificar patrones ocultos y relaciones significativas que no son evidentes a simple vista.

####Ciencia de datos

In [ ]:
#La función help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
#Otra forma de obtener ayuda es utilizando ?
len?

In [ ]:
#Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?

In [ ]:

L?

In [ ]:
#Ejemplo de funcion
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

IPython Magic Commands


In [2]:
#Sirve para evaluar el desempeño de una expresión en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

76.6 µs ± 15.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
#Con doble porcenaje podemos evaluar el desempeño en cunato tiempo de más de una lómea de código
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

82.3 µs ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [5]:
!echo "hello world"

hello world


In [6]:
!pwd

/content


In [7]:
!ls

sample_data


In [8]:
message = "hello from Python"

In [9]:
!echo {message}

hello from Python


In [10]:
%cd /content/

/content


In [11]:
%ls

sample_data/


Understanding Data types in Python

In [12]:
#Importa numpy y renombralo como np
import numpy as np

In [14]:
#arreglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [15]:
#Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [16]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [17]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [18]:
#Cuando el argumento de np.array es una iteración anidad genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])