<a href="https://colab.research.google.com/github/175329/Mineria-de-datos/blob/main/MineriaDeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de datos

##Primer parcial

###Introducción

####Conceptos

Minería de datos: Es una disciplina que utiliza técnicas de análisis estadístico y aprendizaje automático para extraer información valiosa de grandes conjuntos de datos. Este proceso implica la exploración y análisis de datos para identificar patrones ocultos y relaciones significativas que no son evidentes a simple vista.

####Ciencia de datos

In [ ]:
#La función help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
#Otra forma de obtener ayuda es utilizando ?
len?

In [ ]:
#Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?

In [ ]:

L?

In [ ]:
#Ejemplo de funcion
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

IPython Magic Commands


In [ ]:
#Sirve para evaluar el desempeño de una expresión en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

76.6 µs ± 15.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#Con doble porcenaje podemos evaluar el desempeño en cunato tiempo de más de una lómea de código
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

82.3 µs ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [ ]:
!echo "hello world"

hello world


In [ ]:
!pwd

/content


In [ ]:
!ls

sample_data


In [ ]:
message = "hello from Python"

In [ ]:
!echo {message}

hello from Python


In [ ]:
%cd /content/

/content


In [ ]:
%ls

sample_data/


Understanding Data types in Python

In [ ]:
#Importa numpy y renombralo como np
import numpy as np

In [ ]:
#arreglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
#Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
#Cuando el argumento de np.array es una iteración anidad genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays from Scratch

In [ ]:
import numpy as np
#Crear un arreglo de enteros de longitud 10 lleno de ceros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Crear un arreglo de punto flotante de 3x5 lleno de unos
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#Crear un arreglo de 3x5 lleno de 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
#Crear un arreglo lleno con una secuencia lineal
# Comenzando en 0, terminando en 20, avanzando de 2 en 2
# (esto es similar a la función incorporada range())
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#Crear un array de cinco valores distribuidos uniformemente entre 0 y 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Crear un arreglo de 3x3 con valores aleatorios
# distribuidos uniformemente entre 0 y 1
np.random.random((3, 3))

array([[0.64989252, 0.90747762, 0.52328595],
       [0.51873686, 0.93242036, 0.71994933],
       [0.3266828 , 0.01534294, 0.93979983]])

In [ ]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.43269694, -0.23446967, -0.97546252],
       [ 1.58282422,  0.10917898,  0.04211999],
       [ 0.74582587,  1.4899103 ,  0.1371881 ]])

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 4, 0],
       [3, 5, 4],
       [7, 8, 0]])

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

The Basics of NumPy Arrays


In [ ]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
print("dtype:", x3.dtype)

dtype: int64


In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

np.int64(5)

In [ ]:
x1[3]

np.int64(3)

In [ ]:
x1[4]

np.int64(7)

In [ ]:
x1[-1]

np.int64(9)

In [ ]:
x1[-2]

np.int64(7)

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0, 0]

np.int64(3)

In [ ]:
x2[2, 0]

np.int64(1)

In [ ]:
x2[2, -1]

np.int64(7)

In [ ]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

####📊 Análisis Estadístico Básico con NumPy


In [ ]:
import numpy as np

In [ ]:
#Media
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


In [ ]:
#Promedio (Average) y Promedio Ponderado
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [ ]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


In [ ]:
#Mediana
mediana = np.median(data)
print(mediana)

3.0


In [ ]:
#Varianza y Desviación Estándar
#var -> varianza
#std -> desviación estándar
varianza = np.var(data)
desviacion = np.std(data)
print(varianza)
print(desviacion)

2.0
1.4142135623730951


In [ ]:
#Generación de Datos Aleatorios
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


In [ ]:
#Correlación
corr = np.corrcoef([1,2,3], [1,5,7])
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]


####Cuadros estadísticos

In [1]:
import numpy as np
import pandas as pd
from io import StringIO

raw = """Marca temporal\tNúmero de matrícula\t¿Cuántos años cumplidos tienes?\t¿Has realizado programas utilizando Python?\t¿Has utilizado Google Colab?\t¿Tienes cuenta de GitHub?
19/01/2026 18:32:18\t178920\t22\tSi\tNo\tSi
19/01/2026 18:32:23\t182712\t21\tSi\tNo\tSi
19/01/2026 18:32:25\t180370\t26\tSi\tSi\tSi
19/01/2026 18:32:27\t182570\t21\tSi\tSi\tSi
19/01/2026 18:32:28\t177622\t24\tSi\tNo\tSi
19/01/2026 18:32:29\t175166\t22\tSi\tSi\tSi
19/01/2026 18:32:30\t177573\t22\tSi\tSi\tSi
19/01/2026 18:32:35\t178430\t21\tSi\tSi\tSi
19/01/2026 18:32:38\t179169\t23\tSi\tNo\tSi
19/01/2026 18:32:41\t177263\t22\tSi\tSi\tSi
19/01/2026 18:32:48\t179884\t23\tSi\tNo\tSi
19/01/2026 18:32:48\t183016\t22\tSi\tNo\tSi
19/01/2026 18:32:50\t179033\t23\tSi\tSi\tNo
19/01/2026 18:32:54\t178218\t22\tSi\tNo\tSi
19/01/2026 18:32:55\t178446\t22\tSi\tSi\tSi
19/01/2026 18:33:00\t178166\t22\tSi\tSi\tNo
19/01/2026 18:33:02\t177406\t22\tSi\tNo\tSi
19/01/2026 18:33:05\t177192\t22\tSi\tSi\tSi
19/01/2026 18:33:08\t182451\t21\tSi\tNo\tSi
19/01/2026 18:33:08\t171513\t24\tNo\tNo\tSi
19/01/2026 18:33:09\t181619\t21\tSi\tNo\tSi
19/01/2026 18:33:12\t182298\t23\tSi\tNo\tSi
19/01/2026 18:33:14\t181419\t24\tNo\tNo\tSi
19/01/2026 18:33:32\t177291\t21\tSi\tSi\tSi
19/01/2026 18:33:42\t182085\t22\tSi\tNo\tSi
19/01/2026 18:33:53\t176453\t22\tSi\tNo\tSi
19/01/2026 18:34:04\t176263\t24\tSi\tNo\tSi
19/01/2026 18:34:06\t179997\t21\tSi\tNo\tSi
19/01/2026 18:36:21\t175842\t23\tSi\tNo\tNo
19/01/2026 20:19:21\t179913\t20\tSi\tNo\tSi
19/01/2026 20:19:48\t177301\t22\tSi\tSi\tNo
19/01/2026 20:20:06\t183060\t21\tSi\tNo\tSi
19/01/2026 20:20:08\t177935\t22\tSi\tSi\tSi
19/01/2026 20:20:19\t177700\t20\tSi\tSi\tSi
19/01/2026 20:20:26\t178318\t24\tSi\tSi\tSi
19/01/2026 20:20:27\t174653\t24\tSi\tNo\tSi
19/01/2026 20:20:29\t177139\t21\tSi\tNo\tSi
19/01/2026 20:20:31\t173479\t25\tSi\tNo\tNo
19/01/2026 20:20:39\t175588\t23\tNo\tNo\tSi
19/01/2026 20:20:45\t178774\t23\tSi\tSi\tSi
19/01/2026 20:20:45\t175031\t23\tSi\tNo\tNo
19/01/2026 20:20:49\t178396\t21\tSi\tSi\tSi
19/01/2026 20:20:49\t172068\t23\tNo\tNo\tNo
19/01/2026 20:20:50\t174197\t23\tNo\tNo\tSi
19/01/2026 20:20:55\t178584\t22\tSi\tNo\tSi
19/01/2026 20:20:55\t175329\t24\tSi\tNo\tSi
19/01/2026 20:20:56\t177685\t22\tSi\tSi\tSi
19/01/2026 20:20:57\t178678\t22\tNo\tNo\tSi
19/01/2026 20:21:04\t177143\t22\tSi\tNo\tSi
19/01/2026 20:21:07\t182318\t26\tSi\tNo\tSi
19/01/2026 20:21:27\t182377\t20\tSi\tNo\tSi
19/01/2026 20:21:34\t179419\t22\tSi\tNo\tNo
19/01/2026 20:21:35\t181662\t21\tSi\tNo\tSi
19/01/2026 20:21:38\t181760\t21\tSi\tNo\tSi
19/01/2026 20:22:06\t177888\t22\tSi\tNo\tSi
19/01/2026 20:22:15\t176535\t25\tSi\tNo\tSi
19/01/2026 20:22:29\t179862\t21\tSi\tNo\tSi
19/01/2026 20:22:32\t178378\t22\tSi\tNo\tSi
19/01/2026 20:22:50\t177451\t22\tSi\tNo\tSi
19/01/2026 20:23:15\t179804\t21\tSi\tNo\tSi
"""

# Cargar datos
df = pd.read_csv(StringIO(raw), sep='\t')
df.columns = [c.strip() for c in df.columns]

# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce')
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

In [2]:
df.head()

Marca temporal  Número de matrícula  ¿Cuántos años cumplidos tienes?  \
0  19/01/2026 18:32:18               178920                               22   
1  19/01/2026 18:32:23               182712                               21   
2  19/01/2026 18:32:25               180370                               26   
3  19/01/2026 18:32:27               182570                               21   
4  19/01/2026 18:32:28               177622                               24   

  ¿Has realizado programas utilizando Python? ¿Has utilizado Google Colab?  \
0                                          Si                           No   
1                                          Si                           No   
2                                          Si                           Si   
3                                          Si                           Si   
4                                          Si                           No   

  ¿Tienes cuenta de GitHub?  edad  prog_python  usa_colab  cuenta_github  
0                        Si    22         True      False           True  
1                        Si    21         True      False           True  
2                        Si    26         True       True           True  
3                        Si    21         True       True           True  
4                        Si    24         True      False           True

In [3]:
# A NumPy
edad = df['edad'].to_numpy(dtype=float)
prog_py = df['prog_python'].to_numpy(dtype=bool)
usa_colab = df['usa_colab'].to_numpy(dtype=bool)
cuenta_gh = df['cuenta_github'].to_numpy(dtype=bool)

In [7]:
#interpolacion de cadena de caracteres
print(f'ndarray edad primeros 5 elementos: {edad[:5]}')
print(f'ndarray prog_py primeros 5 elementos: {prog_py[:5]}')
print(f'ndarray usa_colab primeros 5 elementos: {usa_colab[:5]}')
print(f'ndarray cuenta_gh ultimos 5 elementos: {cuenta_gh[-5:]}')


ndarray edad primeros 5 elementos: [22. 21. 26. 21. 24.]
ndarray prog_py primeros 5 elementos: [ True  True  True  True  True]
ndarray usa_colab primeros 5 elementos: [False False  True  True False]
ndarray cuenta_gh ultimos 5 elementos: [ True  True  True  True  True]


In [10]:
# Descriptivos de edad (NumPy)
summary_age = {
    'n': int(edad.size),
    'min': float(np.min(edad)),
    'p25': float(np.percentile(edad, 25)),
    'mediana': float(np.median(edad)),
    'media': float(np.mean(edad)),
    'p75': float(np.percentile(edad, 75)),
    'max': float(np.max(edad)),
    'rango(ptp)': float(np.ptp(edad)),
    'var_muestral': float(np.var(edad, ddof=1)),
    'std_muestral': float(np.std(edad, ddof=1)),
    'cv': float(np.std(edad, ddof=1)/np.mean(edad)),
}
summary_age

{'n': 60,
 'min': 20.0,
 'p25': 21.0,
 'mediana': 22.0,
 'media': 22.3,
 'p75': 23.0,
 'max': 26.0,
 'rango(ptp)': 6.0,
 'var_muestral': 1.8406779661016948,
 'std_muestral': 1.3567158752302173,
 'cv': 0.06083927691615324}

In [13]:
# Frecuencias (NumPy)
freq_python = {'Si': int(np.count_nonzero(prog_py)), 'No': int(edad.size - np.count_nonzero(prog_py))}
freq_colab  = {'Si': int(np.count_nonzero(usa_colab)), 'No': int(edad.size - np.count_nonzero(usa_colab))}
freq_gh     = {'Si': int(np.count_nonzero(cuenta_gh)), 'No': int(edad.size - np.count_nonzero(cuenta_gh))}

In [14]:
print(f'Frecuencia de utilizar python: {freq_python}')
print(f'Frecuencia de usar colab: {freq_colab}')
print(f'Frecuencia de usar github: {freq_gh}')

Frecuencia de utilizar python: {'Si': 54, 'No': 6}
Frecuencia de usar colab: {'Si': 18, 'No': 42}
Frecuencia de usar github: {'Si': 52, 'No': 8}


In [15]:
# Tablas cruzadas (NumPy)
def tabla2x2(a, b):
    t = np.zeros((2,2), dtype=int)
    t[1,1] = np.count_nonzero(a & b)
    t[1,0] = np.count_nonzero(a & ~b)
    t[0,1] = np.count_nonzero(~a & b)
    t[0,0] = np.count_nonzero(~a & ~b)
    return t

tab_py_colab = tabla2x2(prog_py, usa_colab)
tab_py_gh    = tabla2x2(prog_py, cuenta_gh)
tab_colab_gh = tabla2x2(usa_colab, cuenta_gh)


In [16]:
print(f'Tabla python vs colab \n{tab_py_colab}')
print(f'Tabla python vs github \n{tab_py_gh}')
print(f'Tabla colab vs github \n{tab_colab_gh}')

Tabla python vs colab 
[[ 6  0]
 [36 18]]
Tabla python vs github 
[[ 1  5]
 [ 7 47]]
Tabla colab vs github 
[[ 5 37]
 [ 3 15]]


In [17]:
# Medias de edad por grupo (NumPy)
means_by_group = {
    'edad_promedio_Python': {'Si': float(np.mean(edad[prog_py])) if np.any(prog_py) else np.nan,
                             'No': float(np.mean(edad[~prog_py])) if np.any(~prog_py) else np.nan},
    'edad_promedio_Colab':  {'Si': float(np.mean(edad[usa_colab])) if np.any(usa_colab) else np.nan,
                             'No': float(np.mean(edad[~usa_colab])) if np.any(~usa_colab) else np.nan},
    'edad_promedio_GitHub': {'Si': float(np.mean(edad[cuenta_gh])) if np.any(cuenta_gh) else np.nan,
                             'No': float(np.mean(edad[~cuenta_gh])) if np.any(~cuenta_gh) else np.nan},
}

means_by_group

{'edad_promedio_Python': {'Si': 22.203703703703702, 'No': 23.166666666666668},
 'edad_promedio_Colab': {'Si': 22.11111111111111, 'No': 22.38095238095238},
 'edad_promedio_GitHub': {'Si': 22.21153846153846, 'No': 22.875}}