<a href="https://colab.research.google.com/github/175329/Mineria-de-datos/blob/main/MineriaDeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de datos

##Primer parcial

###Introducción

####Conceptos

Minería de datos: Es una disciplina que utiliza técnicas de análisis estadístico y aprendizaje automático para extraer información valiosa de grandes conjuntos de datos. Este proceso implica la exploración y análisis de datos para identificar patrones ocultos y relaciones significativas que no son evidentes a simple vista.

####Ciencia de datos

In [ ]:
#La función help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
#Otra forma de obtener ayuda es utilizando ?
len?

In [ ]:
#Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?

In [ ]:

L?

In [ ]:
#Ejemplo de funcion
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

IPython Magic Commands


In [ ]:
#Sirve para evaluar el desempeño de una expresión en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

76.6 µs ± 15.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#Con doble porcenaje podemos evaluar el desempeño en cunato tiempo de más de una lómea de código
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

82.3 µs ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [ ]:
!echo "hello world"

hello world


In [ ]:
!pwd

/content


In [ ]:
!ls

sample_data


In [ ]:
message = "hello from Python"

In [ ]:
!echo {message}

hello from Python


In [ ]:
%cd /content/

/content


In [ ]:
%ls

sample_data/


Understanding Data types in Python

In [ ]:
#Importa numpy y renombralo como np
import numpy as np

In [ ]:
#arreglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
#Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
#Cuando el argumento de np.array es una iteración anidad genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays from Scratch

In [2]:
import numpy as np
#Crear un arreglo de enteros de longitud 10 lleno de ceros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
#Crear un arreglo de punto flotante de 3x5 lleno de unos
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
#Crear un arreglo de 3x5 lleno de 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [5]:
#Crear un arreglo lleno con una secuencia lineal
# Comenzando en 0, terminando en 20, avanzando de 2 en 2
# (esto es similar a la función incorporada range())
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
#Crear un array de cinco valores distribuidos uniformemente entre 0 y 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
# Crear un arreglo de 3x3 con valores aleatorios
# distribuidos uniformemente entre 0 y 1
np.random.random((3, 3))

array([[0.64989252, 0.90747762, 0.52328595],
       [0.51873686, 0.93242036, 0.71994933],
       [0.3266828 , 0.01534294, 0.93979983]])

In [8]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.43269694, -0.23446967, -0.97546252],
       [ 1.58282422,  0.10917898,  0.04211999],
       [ 0.74582587,  1.4899103 ,  0.1371881 ]])

In [9]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 4, 0],
       [3, 5, 4],
       [7, 8, 0]])

In [10]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

The Basics of NumPy Arrays


In [12]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [13]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [14]:
print("dtype:", x3.dtype)

dtype: int64


In [15]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [16]:
x1

array([5, 0, 3, 3, 7, 9])

In [17]:
x1[0]

np.int64(5)

In [18]:
x1[3]

np.int64(3)

In [19]:
x1[4]

np.int64(7)

In [20]:
x1[-1]

np.int64(9)

In [21]:
x1[-2]

np.int64(7)

In [25]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
x2[0, 0]

np.int64(3)

In [28]:
x2[2, 0]

np.int64(1)

In [29]:
x2[2, -1]

np.int64(7)

In [30]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [31]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

####📊 Análisis Estadístico Básico con NumPy


In [32]:
import numpy as np

In [33]:
#Media
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


In [34]:
#Promedio (Average) y Promedio Ponderado
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [39]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


In [40]:
#Mediana
mediana = np.median(data)
print(mediana)

3.0


In [41]:
#Varianza y Desviación Estándar
#var -> varianza
#std -> desviación estándar
varianza = np.var(data)
desviacion = np.std(data)
print(varianza)
print(desviacion)

2.0
1.4142135623730951


In [37]:
#Generación de Datos Aleatorios
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


In [42]:
#Correlación
corr = np.corrcoef([1,2,3], [1,5,7])
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]
